version: "3"

services:
  graph:
    image: janusgraph/janusgraph:0.5.2
    environment:
      JANUS_PROPS_TEMPLATE: cassandra-es
      janusgraph.storage.backend: cql
      janusgraph.storage.hostname: db
      janusgraph.index.search.hostname: index
    ports:
      - "8182:8182"
      - "8184:8184"
    depends_on:
      - db
      - index
  db:
    image: scylladb/scylla:4.2.1
    ports:
      # REST API
      - "10000:10000"
      # CQL ports (native_transport_port)
      - "9042:9042"
      # Thrift (rpc_port)
      - "9160:9160"
      # Internode
      - "7000:7000"
      - "7001:7001"
      # JMX
      - "7199:7199"
      # Prometheus monitoring
      - "9180:9180"
      - "9100:9100"
#     healthcheck:
#       test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
#       interval: 30s
#       timeout: 10s
#       retries: 5
    volumes:
      - ./data/db/data:/var/lib/db
  index:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 1s
      timeout: 30s
      retries: 30
    user: "1000"
    volumes:
     - ./data/elasticsearch/data:/usr/share/elasticsearch/data
