version: "3"

services:
  graph:
    container_name: janusgraph
    image: janusgraph/janusgraph:0.5.2
    environment:
      JANUS_PROPS_TEMPLATE: cassandra-es
      janusgraph.storage.backend: cql
      janusgraph.storage.hostname: db
      janusgraph.index.search.hostname: index
    ports:
      - "8182:8182"
      - "8184:8184"
    depends_on:
      - db
      - index
      
  db:
    container_name: scylladb
    image: scylladb/scylla:4.2.1
    ports:
      # REST API
      - "10000:10000"
      # CQL ports (native_transport_port)
      - "9042:9042"
      # Thrift (rpc_port)
      - "9160:9160"
      # Internode
      - "7000:7000"
      - "7001:7001"
      # JMX
      - "7199:7199"
      # Prometheus monitoring
      - "9180:9180"
      - "9100:9100"
#     healthcheck:
#       test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
#       interval: 30s
#       timeout: 10s
#       retries: 5
    volumes:
      - ./data/db/data:/var/lib/db
  index:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - node.name=kifarunix-demo-es
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
